# Generated by Django 4.0 on 2021-12-10 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=40)),
                ('isbn', models.CharField(max_length=40)),
                ('publishingCompany', models.CharField(max_length=40)),
                ('publicationDate', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='livros.categoria')),
            ],
        ),
    ]
